name: MADS Design Token Generator
description: MADS Design Token Generator

inputs:
  FIGMA_ACCESS_TOKEN:
    required: true
  GITHUB_TOKEN:
    required: true

runs:
  using: "node20"
  main: dist/index.js
