name: Generate & PR
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - uses: pnpm/action-setup@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version-file: '.nvmrc'
      #     cache: 'pnpm'
      
      - uses: jinseoplee/action-test/mads-design-token-generator-action@actions
        with:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update design token"
          title: "chore: update design token"
          body: "chore: update design token"
          branch: update-tokens-${{ github.run_id }}
          base: main
