name: Deploy Applications
run-name: Deploy Applications - ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      use-qa-checker:
        description: "Use QA Checker"
        required: true
        default: "true"
        type: boolean


jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello, World!"





